// This file is generated by icon spritesheet generator

export const iconNames = [
  "Zap",
  "X",
  "TriangleAlert",
  "Trash2",
  "Sun",
  "SunMoon",
  "ShieldCheck",
  "Search",
  "Rocket",
  "Pilcrow",
  "Palette",
  "Moon",
  "Menu",
  "Info",
  "Hash",
  "Github",
  "Ghost",
  "FileText",
  "Code",
  "Clock",
  "ClipboardCopy",
  "ClipboardCheck",
  "ChevronRight",
  "ChevronDown",
  "Bot",
  "ArrowRight",
  "ArrowLeft",
] as const

export type IconName = typeof iconNames[number]
