# syntax = docker/dockerfile:1.4

ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-slim AS base

LABEL fly_launch_runtime="Node.js"
WORKDIR /app
ENV NODE_ENV=production

ARG PNPM_VERSION=10.18.0
RUN npm install -g pnpm@$PNPM_VERSION

# --- Build stage ---
# We consume the docs generated by the CI
FROM base AS build

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3 && \
    rm -rf /var/lib/apt/lists/*

COPY .npmrc package.json ./
RUN pnpm install --prod=false


COPY . .

RUN pnpm run build

# Prune dev deps
RUN pnpm prune --prod

# --- Runtime stage ---
FROM base

COPY --from=build /app /app

EXPOSE 3000
CMD ["pnpm","run","start"]