name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


  deploy-docs:
    name: "🚀 Deploy Docs"
    runs-on: ubuntu-latest
    environment:
      name: docs-release
      url: ${{ steps.deploy.outputs.app_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: forge-42/fly-deploy@v1.0.0-rc.1
        id: deploy
        env:
          FLY_ORG: ${{ vars.FLY_ORG }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_REGION: fra
        with:
          workspace_name: docs
          app_name: react-router-devtools-docs-release
          use_isolated_workspace: true
