name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  FLY_ORG: ${{ vars.FLY_ORG }}

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-preview:
    name: "🚀 Deploy Docs"
    runs-on: ubuntu-latest
    needs: [npm-publish]
    steps:
    - uses: forge-42/fly-deploy@main
      id: deploy
      env:
        FLY_ORG: ${{ vars.FLY_ORG }}
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        FLY_REGION: fra
      with:
        app_name: ${{ env.FLY_ORG }}-production
        use_isolated_workspace: true
        workspace_name: docs