name: 🚀 pkg-pr-new
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - run: npx pkg-pr-new publish



  deploy-preview:
    name: "🚀 Deploy Docs"
    uses: forge42dev/workflows/.github/workflows/deploy-to-fly.yaml@monorepo-matrix
    with:
      workspace_name: docs
      github_environment: "docs-previev"
    secrets:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
