name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  FLY_ORG: ${{ vars.FLY_ORG }}

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-preview:
    name: "🚀 Deploy Docs"
    needs: [npm-publish]
    uses: forge42dev/workflows/.github/workflows/deploy-to-fly.yaml@monorepo-matrix
    with:
      workspace_name: docs
      set_cwd_to_workspace: true
      github_environment: "docs-release"
    secrets:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
